source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CroptateView_Example', :exclusive => true do
  pod "CroptateView", :path => "../"
end

target 'CroptateView_Tests', :exclusive => true do
  pod "CroptateView", :path => "../"

  
end
